name: Fetch API data
on:
  push:
    branches:
      - main
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch data
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/users/octocat > data.json
      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "${timestamp}" || exit 0
          git push
